export const HEAL_PRESET_DEFAULT = Object.freeze({
  globeCost: 1,
  healAmountHp: 500,
  castDurationMs: 250,
  cooldownMs: 1000,
  requireDamagedOrb: true,
  consumeOnFailedCast: false,
  shaderPulseLuminanceBoostPct: 25,
  shaderPulseCenterAlphaPct: 10,
  shaderPulsePointLightIntensityPct: 25,
  shaderPulsePointLightDistancePct: 10,
  shaderPulseGoldMixPct: 25,
  shaderPulseDurationMs: 150,
  shaderPulseEasing: "easeInOutQuad",
});
