export const STARS_FIELD_CONFIG = Object.freeze({
  targetStarCount: 3000,
  enableClipMask: false,
  showDebugOutline: true,
  targetCellSizeW: 76,
  minRegionAreaW2: 64000,
  renderCullMarginW: 0,
  overscanScale: 1.0,
  candidateOrdinals: 4,
  jitterRatio: 0.42,
  maxJitterW: 54,
  seedSalt: "stars-field-v1",
  parallaxLayers: Object.freeze([
    Object.freeze({
      id: "far",
      parallaxRatio: 0.18,
      overscanScale: 1.0,
      stroke: "#ff9f2f",
    }),
    Object.freeze({
      id: "mid",
      parallaxRatio: 0.48,
      overscanScale: 1.0,
      stroke: "#38d66b",
    }),
    Object.freeze({
      id: "near",
      parallaxRatio: 0.72,
      overscanScale: 1.0,
      stroke: "#4aa3ff",
    }),
  ]),
  spawnChances: Object.freeze({
    primary: Object.freeze([0.28, 0.97]),
    secondary: Object.freeze([0.01, 0.72]),
    tertiary: Object.freeze([0.0, 0.34]),
    quaternary: Object.freeze([0.0, 0.10]),
  }),
  highlight: Object.freeze({
    chanceRange: Object.freeze([0.0008, 0.015]),
    denseAreaMultiplier: 1.9,
    radiusMultiplierRange: Object.freeze([1.8, 3.0]),
    opacityBoostRange: Object.freeze([0.08, 0.22]),
    haloOpacityRange: Object.freeze([0.06, 0.18]),
    haloRadiusMultiplierRange: Object.freeze([2.8, 5.2]),
  }),
  depthBands: Object.freeze([
    Object.freeze({
      id: "far",
      weight: 0.60,
      radiusRangePx: Object.freeze([0.9, 1.75]),
      opacityRange: Object.freeze([0.28, 0.56]),
      parallaxRatio: 0.18,
      palette: Object.freeze([
        "#9fbfff",
        "#8dd6ff",
        "#8ef2d2",
        "#ffd982",
        "#ffb39e",
        "#ffb8e2",
        "#bca6ff",
        "#f8fbff",
      ]),
    }),
    Object.freeze({
      id: "mid",
      weight: 0.28,
      radiusRangePx: Object.freeze([1.55, 2.8]),
      opacityRange: Object.freeze([0.58, 0.90]),
      parallaxRatio: 0.48,
      palette: Object.freeze([
        "#f8fbff",
        "#d1efff",
        "#b8ffef",
        "#ffe89c",
        "#ffc8a7",
        "#ffbddc",
        "#cab8ff",
        "#fff8d4",
      ]),
    }),
    Object.freeze({
      id: "near",
      weight: 0.12,
      radiusRangePx: Object.freeze([2.2, 4.4]),
      opacityRange: Object.freeze([0.82, 1.00]),
      parallaxRatio: 0.72,
      palette: Object.freeze([
        "#ffffff",
        "#e0f7ff",
        "#d5fff2",
        "#fff0ab",
        "#ffd5a6",
        "#ffc7bd",
        "#ffd0f3",
        "#d9ccff",
        "#fffdf2",
      ]),
    }),
  ]),
});
