export const STARS_FIELD_CONFIG = Object.freeze({
  targetStarCount: 3000,
  targetCellSizeW: 76,
  overscanScale: 1.0,
  candidateOrdinals: 4,
  jitterRatio: 0.42,
  maxJitterW: 54,
  seedSalt: "stars-field-v1",
  parallaxLayers: Object.freeze([
    Object.freeze({
      id: "far",
      parallaxRatio: 0.18,
      overscanScale: 1.0,
      stroke: "#ff9f2f",
      starCountWeight: 0.50,
      radiusRangePx: Object.freeze([0.9, 1.8]),
      opacityRange: Object.freeze([0.28, 0.58]),
      palette: Object.freeze(["#f8fbff", "#d8efff", "#bde7ff", "#ffe8a8", "#ffd1c2", "#d7c9ff"]),
      highlightChance: 0.010,
    }),
    Object.freeze({
      id: "medium",
      parallaxRatio: 0.36,
      overscanScale: 1.0,
      stroke: "#42d98c",
      starCountWeight: 0.32,
      radiusRangePx: Object.freeze([1.1, 2.2]),
      opacityRange: Object.freeze([0.42, 0.76]),
      palette: Object.freeze(["#ffffff", "#dff8ff", "#c8fff0", "#ffe8a8", "#ffd2a8", "#ffcde7"]),
      highlightChance: 0.016,
    }),
    Object.freeze({
      id: "close",
      parallaxRatio: 0.56,
      overscanScale: 1.0,
      stroke: "#49a8ff",
      starCountWeight: 0.18,
      radiusRangePx: Object.freeze([1.5, 3.0]),
      opacityRange: Object.freeze([0.60, 1.00]),
      palette: Object.freeze(["#ffffff", "#ecfbff", "#fff0b8", "#ffd7b8", "#ffd3ee", "#ddd4ff"]),
      highlightChance: 0.028,
    }),
  ]),
});
