import { VOICE_MODES } from "./voice-config.js";

export const META_COMMANDS = Object.freeze({
  WAKE_TOKEN: "orbis",
});

export const WAKE_TOKEN = META_COMMANDS.WAKE_TOKEN;
export const WAKE_TOKEN_ALIASES = Object.freeze([
  "orbus",
  "orbis",
  "orbisz",
  "orbyss",
  "obis",
  "orbizz",
  "obess",
  "orbess",
  "orvess",
]);
export const WAKE_TOKENS = Object.freeze([WAKE_TOKEN, ...WAKE_TOKEN_ALIASES]);

export const SPELLS = [
  {
    id: "domus",
    phrase: "domus",
    aliases: ["dohmus", "domas", "dohmas", "thomas", "dumbass"],
    minConfidence: 0.62,
    cooldownMs: 800,
    allowedAxes: ["y"],
    fixedSlot: "UD",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.domus",
  },
  {
    id: "school_ignis",
    phrase: "ignis",
    aliases: ["ingnis", "ignis"],
    minConfidence: 0.6,
    cooldownMs: 0,
    allowedAxes: ["y"],
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_select",
    school: "ignis",
  },
  {
    id: "school_fridgis",
    phrase: "fridgis",
    aliases: ["fridge" , "frijuss", "fridjuss", "fridgidis", "fidgidis", "frigedis", "frijis", "frigidis"],
    minConfidence: 0.6,
    cooldownMs: 0,
    allowedAxes: ["x"],
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_select",
    school: "fridgis",
  },
  {
    id: "school_electrum",
    phrase: "electrum",
    aliases: ["elektrum", "alectrum", "ilectrum"],
    minConfidence: 0.6,
    cooldownMs: 0,
    allowedAxes: ["z"],
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_select",
    school: "electrum",
  },
  {
    id: "class_sanctus",
    phrase: "sanctus",
    aliases: ["sanktus", "sanctas", "sanctum", "sanktum"],
    minConfidence: 0.6,
    cooldownMs: 0,
    allowedAxes: ["x", "y", "z"],
    fixedSlot: "UD",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.class_select",
    classKey: "sanctus",
  },
  {
    id: "class_radius",
    phrase: "radius",
    aliases: ["radyus", "radiuz", "raydus"],
    minConfidence: 0.6,
    cooldownMs: 0,
    allowedAxes: ["x", "y", "z"],
    fixedSlot: "LR",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.class_select",
    classKey: "radius",
  },
  {
    id: "class_rota",
    phrase: "rota",
    aliases: ["rohta", "rotah" , "rodah", "rowdah"],
    minConfidence: 0.6,
    cooldownMs: 0,
    allowedAxes: ["x", "y", "z"],
    fixedSlot: "FB",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.class_select",
    classKey: "rota",
  },
  {
    id: "ignis_sanctus",
    phrase: "ignis sanctus",
    aliases: ["ingnis sanctus", "ignis sanctus", "ignis sanktus", "ignis sanctas", "ignis sanctum", "ignis sanktum"],
    minConfidence: 0.62,
    cooldownMs: 1000,
    allowedAxes: ["y"],
    fixedSlot: "UD",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_shield",
    school: "ignis",
    classKey: "sanctus",
  },
  {
    id: "ignis_radius",
    phrase: "ignis radius",
    aliases: ["ingnis radius", "ignis radyus", "ignis radiuz", "ignis raydus"],
    minConfidence: 0.62,
    cooldownMs: 1000,
    allowedAxes: ["y"],
    fixedSlot: "LR",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_ray",
    school: "ignis",
    classKey: "radius",
  },
  {
    id: "ignis_rota",
    phrase: "ignis rota",
    aliases: ["ingnis rota", "ignis rotah", "ignis rohta"],
    minConfidence: 0.64,
    cooldownMs: 1100,
    allowedAxes: ["y"],
    fixedSlot: "FB",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_aoe",
    school: "ignis",
    classKey: "rota",
  },
  {
    id: "fridgis_sanctus",
    phrase: "fridgis sanctus",
    aliases: [
      "fridgis sanctus",
      "fridgis sanctum",
      "fridgidis sanctus",
      "fidgidis sanctus",
      "frigedis sanctus",
      "frigidis sanktus",
      "frigidis sanctum"
    ],
    minConfidence: 0.62,
    cooldownMs: 1000,
    allowedAxes: ["x"],
    fixedSlot: "UD",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_shield",
    school: "fridgis",
    classKey: "sanctus",
  },
  {
    id: "fridgis_radius",
    phrase: "fridgis radius",
    aliases: [
      "fridgis radius",
      "fridgidis radius",
      "fidgidis radius",
      "frigedis radius",
      "frigidis radyus"
    ],
    minConfidence: 0.62,
    cooldownMs: 1000,
    allowedAxes: ["x"],
    fixedSlot: "LR",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_ray",
    school: "fridgis",
    classKey: "radius",
  },
  {
    id: "fridgis_rota",
    phrase: "fridgis rota",
    aliases: ["fridgis rota", "fridgidis rota", "fidgidis rota", "frigedis rota", "frigidis rohta"],
    minConfidence: 0.64,
    cooldownMs: 1100,
    allowedAxes: ["x"],
    fixedSlot: "FB",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_aoe",
    school: "fridgis",
    classKey: "rota",
  },
  {
    id: "electrum_sanctus",
    phrase: "electrum sanctus",
    aliases: ["elektrum sanctus", "electrum sanktus", "electrum sanctas", "electrum sanctum", "elektrum sanctum"],
    minConfidence: 0.64,
    cooldownMs: 1000,
    allowedAxes: ["z"],
    fixedSlot: "UD",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_shield",
    school: "electrum",
    classKey: "sanctus",
  },
  {
    id: "electrum_radius",
    phrase: "electrum radius",
    aliases: ["elektrum radius", "electrum radyus", "electrum radiuz"],
    minConfidence: 0.64,
    cooldownMs: 1000,
    allowedAxes: ["z"],
    fixedSlot: "LR",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_ray",
    school: "electrum",
    classKey: "radius",
  },
  {
    id: "electrum_rota",
    phrase: "electrum rota",
    aliases: ["elektrum rota", "electrum rohta", "electrum rotah"],
    minConfidence: 0.64,
    cooldownMs: 1100,
    allowedAxes: ["z"],
    fixedSlot: "FB",
    gateModes: [VOICE_MODES.GATED_WINDOW, VOICE_MODES.WAKE_TOKEN_OPEN_WORLD],
    intent: "spell.school_aoe",
    school: "electrum",
    classKey: "rota",
  },
];

export const SPELLS_BY_ID = Object.freeze(
  SPELLS.reduce((acc, s) => {
    acc[s.id] = s;
    return acc;
  }, {})
);
